name: ${project.name}
main: com.untamedears.humbug.Humbug
version: ${project.version}
softdepend: [CombatTag, CombatTagPlus]
description: toggles various functionality
author: erocs
authors: [ProgrammerDan, rourke750]
database: false
commands:
  humbug:
    description: Gets and sets Humbugs settings
    usage: /humbug <setting> [<value>]
    permission: humbug.console
  introbook:
    description: Creates the intro book for new players
    usage: /introbook [<playerName>]
    permission: humbug.admin.introbook
  introkit:
    description: Creates an intro kit for new players
    usage: /introkit [<playerName>]
    permission: humbug.admin.introkit
  bahhumbug:
    description: Creates a holiday package
    usage: /bahhumbug
    permission: humbug.admin.bahhumbug
permissions:
  humbug.console:
    description: Console commands for Humbug
    default: false
  humbug.admin:
    description: Admin commands for Humbug
    default: op
    children:
      humbug.admin.introkit: true
      humbug.admin.introbook: true
      humbug.admin.bahhumbug: true
  humbug.admin.introkit:
    description: Access to the /introkit command
    default: false
  humbug.admin.introbook:
    description: Access to the /introbook command
    default: false
  humbug.admin.bahhumbug:
    description: Access to the /bahhumbug command
    default: false
  humbug.admin.invsee:
    description: Access to the /invsee command
    default: false
